name       : fltk
version    : 1.3.3
release    : 3
source     :
    - http://fltk.org/pub/fltk/1.3.3/fltk-1.3.3-source.tar.gz : f8398d98d7221d40e77bc7b19e761adaf2f1ef8bb0c30eceb7beb4f2273d0d97
license    : LGPL-2.0-or-later
component  : programming.library
summary    : FLTK cross-platform C++ toolkit
description: |
    FLTK (pronounced "fulltick") is a cross-platform C++ GUI toolkit for UNIX®/Linux® (X11), Microsoft® Windows®, and MacOS® X. FLTK provides modern GUI functionality without the bloat and supports 3D graphics via OpenGL® and its built-in GLUT emulation.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xft)
setup      : |
    %patch -p1 < $pkgfiles/0001-disable_static_libs.patch
    %configure --prefix=/usr --enable-threads --enable-xft --enable-shared
build      : |
    %make
install    : |
    %make_install
